# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
paginate:     10

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
#markdown:     kramdown
#highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
#title: Jekyll Theme
description: A website designed from Jekyll theme.
keywords: Mao Fagui, Felix
url: https://cowandcat.github.io/
feed: /atom.xml
favicon: https://avatars0.githubusercontent.com/u/1695304?v=3&s=460

#Nav config
nav:
  - text: Home
    url: /index.html
  - text: Categories
    url: /navigations/categories.html
  - text: Archives
    url: /navigations/archives.html
  - text: Contact
    url: /navigations/contact.html
  - text: Links
    url: /navigations/links.html
  - text: Online CV
    url: /Resume/resume_cn.html

#Author config
author:
    name: mfg
    email: maofg92@163.com
    imgRel: true
    imageLink: /images/avatar.png
    simpleIntro: I am Mao Fagui. <br /> Good Good Coding, Day Day Up!
    detailIntro:
      <p>It is the personal blog of Mao Fagui. </p>
      <p>Something interesting, awesome, important, or remarkable will be recorded as blogs here.</p>
      <p>I've been looking for people who share common interests with me. I am very glad to make friends with you.</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: https://github.com/cowandcat.atom
  - class: icon-weibo
    url: http://weibo.com/maofg
  - class: icon-github-alt
    url: https://github.com/cowandcat
#  - class: icon-renren
#    url: http://renren.com
#  - class: icon-github-alt
#    url: http://github.com
#  - class: icon-twitter
#    url: http://twitter.com
# - class: icon-google-plus
#    url: http://google.com

#Links
customLinks:
  - item:
    - text: StrayBirds Blog Templates
      url: https://github.com/minixalpha/StrayBirds
    message: Blog Templates
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: jQuery
      url: http://jquery.com/
    message: Other Links

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-40169250-1

#comment config
disqus:
  config: true
  id: haluomao
 
########Global config
username: haluomao
baseurl:
safe: false
highlighter: rouge #pygments
gems: [jekyll-paginate]

title: MFG's Blog
description: Good Good Coding, Day Day Up!
disqusname: Blogs
themename: kunka
